### ISSUE TITLE
Switch from Ant to Gradle and add CircleCI

### ISSUE THREAD

**Issue by saharati** [saharati/GameOne#9]
Test scripts:

build.grade:
```
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
	compile 'mysql:mysql-connector-java:8.0.15'
	compile 'junit:junit:4.12'
}

jar {
	archiveName = 'MyProject.jar'
	manifest {
		attributes('Class-Path': configurations.runtime
									.collect { 'libs/' + it.name }
									.join(' '))
		attributes('Main-Class': 'com.sahar.MainClass')
	}
}

task copy(type: Copy) {
	into "$buildDir"
	from jar
	
	into("libs") {
		from configurations.compile
	}
}

build.finalizedBy(copy)

gradle.startParameter.showStacktrace = org.gradle.api.logging.configuration.ShowStacktrace.ALWAYS
```

config.yml:
```
# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests and build!
      - run: gradle build
      
      # Save gradle results
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      # Store test results
      - store_test_results:
          path: ~/junit 
```
